version: '3.7'

services:
  nginx:
    image: movie-nginx
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

  web:
    image: movie_tracker:latest
    build: ./flask-app
    container_name: flask-app
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      RECOMMENDATION_HOST: recommendation
      TMDB_API_KEY: ${TMDB_API_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
    restart: always

  recommendation:
    image: recommendation-service:latest
    build: ./recommendation-service
    container_name: recommendation-service
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TMDB_API_KEY: ${TMDB_API_KEY}
    depends_on:
      - db
    restart: always

  db:
    image: movie-db:latest
    build: ./movie-db
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: movie_tracker
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always


volumes:
  mysql_data:
