version: '3.7'

services:
  web:
    image: movie_tracker:latest
    build: ./flask-app
    container_name: flask-app
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TMDB_API_KEY: ${TMDB_API_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
    restart: always

  db:
    image: movie-db:latest
    build: ./movie-db
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: movie_tracker
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
